---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
 
- name: Define standard netpen packages
  set_fact:
      netpen_packages: "{{ __netpen_packages | list }}"
  when: re_packages is not defined

- name: Include os-specific setup
  include_tasks: "setup-{{ ansible_os_family }}.yml"
