---
- name: Install Empire Container
  docker_image:
      name: empireproject/empire

- name: Install Metasploit Container
  docker_image:
      name: metasploitframework/metasploit-framework

- name: Download Responder
  git:
      repo: 'https://github.com/SpiderLabs/Responder'
      dest: /opt/responder

- name: Setup Responder Permissions
  become: true
  file:
      path: /opt/responder
      owner: root
      group: pentesters
      mode: 0775
      recurse: yes

- name: Get smbexec
  git:
      repo: 'https://github.com/brav0hax/smbexec.git'
      dest: /opt/smbexec

- name: Setup smbexec permissions
  become: true
  file:
      path: /opt/smbexec
      owner: root
      group: pentesters
      mode: 0775
      recurse: yes
